import bcrypt from 'bcryptjs';
import { User, Seller, Category, Product, Order, Review, Notification } from '../types/index.ts';

// Precomputed bcrypt hashes for fast startup, or generated at runtime
const adminPasswordHash = bcrypt.hashSync('admin123', 10);
const sellerPasswordHash = bcrypt.hashSync('seller123', 10);
const userPasswordHash = bcrypt.hashSync('user123', 10);

export const initialUsers: User[] = [
  {
    id: 'user-admin-1',
    name: 'Dilshod Rahmatov (Admin)',
    email: 'admin@bozor.uz',
    phone: '+998901234567',
    passwordHash: adminPasswordHash,
    role: 'ADMIN',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: new Date('2026-01-01').toISOString(),
    updatedAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'user-seller-1',
    name: 'Javohir Aliyev (TechnoMall)',
    email: 'seller@bozor.uz',
    phone: '+998939876543',
    passwordHash: sellerPasswordHash,
    role: 'SELLER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: new Date('2026-01-10').toISOString(),
    updatedAt: new Date('2026-01-10').toISOString(),
  },
  {
    id: 'user-customer-1',
    name: 'Anvar Karimov',
    email: 'user@bozor.uz',
    phone: '+998971112233',
    passwordHash: userPasswordHash,
    role: 'CUSTOMER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    createdAt: new Date('2026-02-01').toISOString(),
    updatedAt: new Date('2026-02-01').toISOString(),
  },
];

export const initialSellers: Seller[] = [
  {
    id: 'seller-1',
    userId: 'user-seller-1',
    storeName: 'TechnoMall O‘zbekiston',
    description: 'Zamonaviy smartfonlar, noutbuklar va gadjetlar rasmiy kafolat bilan Toshkent va butun respublika bo‘ylab.',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    phone: '+998939876543',
    address: 'Toshkent sh., Chilonzor tumani, Bunyodkor shoh ko‘chasi 15-uy',
    rating: 4.9,
    totalSales: 1240,
    status: 'APPROVED',
    createdAt: new Date('2026-01-10').toISOString(),
    updatedAt: new Date('2026-01-10').toISOString(),
  },
  {
    id: 'seller-2',
    userId: 'user-admin-1', // second store owned by partner
    storeName: 'ModaStyle & Brendlar',
    description: 'Yevropa va Turkiyaning original kiyim-kechak, sport liboslari va poyabzallari to‘plami.',
    logo: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=150&auto=format&fit=crop&q=80',
    phone: '+998901234567',
    address: 'Toshkent sh., Mirobod tumani, Nukus ko‘chasi 42-uy',
    rating: 4.8,
    totalSales: 890,
    status: 'APPROVED',
    createdAt: new Date('2026-01-15').toISOString(),
    updatedAt: new Date('2026-01-15').toISOString(),
  },
];

export const initialCategories: Category[] = [
  {
    id: 'cat-telefonlar',
    name: 'Telefonlar va Gadjetlar',
    slug: 'telefonlar',
    icon: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=300&auto=format&fit=crop&q=80',
    order: 1,
    isActive: true,
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-kompyuterlar',
    name: 'Kompyuterlar va Noutbuklar',
    slug: 'kompyuterlar',
    icon: 'Laptop',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=300&auto=format&fit=crop&q=80',
    order: 2,
    isActive: true,
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-elektronika',
    name: 'Elektronika va Audio',
    slug: 'elektronika',
    icon: 'Headphones',
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=300&auto=format&fit=crop&q=80',
    order: 3,
    isActive: true,
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-kiyim',
    name: 'Kiyim-kechak',
    slug: 'kiyim-kechak',
    icon: 'Shirt',
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=300&auto=format&fit=crop&q=80',
    order: 4,
    isActive: true,
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-poyabzal',
    name: 'Oyoq kiyim',
    slug: 'oyoq-kiyim',
    icon: 'Footprints',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&auto=format&fit=crop&q=80',
    order: 5,
    isActive: true,
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-uy-rozgor',
    name: 'Uy-ro‘zg‘or buyumlari',
    slug: 'uy-rozgor',
    icon: 'Home',
    image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=300&auto=format&fit=crop&q=80',
    order: 6,
    isActive: true,
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-kosmetika',
    name: 'Kosmetika va Parfyumeriya',
    slug: 'kosmetika',
    icon: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=300&auto=format&fit=crop&q=80',
    order: 7,
    isActive: true,
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-sport',
    name: 'Sport va Fitnes',
    slug: 'sport',
    icon: 'Dumbbell',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=300&auto=format&fit=crop&q=80',
    order: 8,
    isActive: true,
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-bolalar',
    name: 'Bolalar mahsulotlari',
    slug: 'bolalar-mahsulotlari',
    icon: 'Baby',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=300&auto=format&fit=crop&q=80',
    order: 9,
    isActive: true,
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-avto',
    name: 'Avto aksessuarlar',
    slug: 'avto',
    icon: 'Car',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=300&auto=format&fit=crop&q=80',
    order: 10,
    isActive: true,
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-kitoblar',
    name: 'Kitoblar va Kanselyariya',
    slug: 'kitoblar',
    icon: 'BookOpen',
    image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=300&auto=format&fit=crop&q=80',
    order: 11,
    isActive: true,
    createdAt: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-boshqa',
    name: 'Boshqa tovarlar',
    slug: 'boshqa',
    icon: 'Box',
    image: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=300&auto=format&fit=crop&q=80',
    order: 12,
    isActive: true,
    createdAt: new Date('2026-01-01').toISOString(),
  },
];

export const initialProducts: Product[] = [
  // 1
  {
    id: 'prod-iphone-15-pro-max',
    sellerId: 'seller-1',
    categoryId: 'cat-telefonlar',
    name: 'Apple iPhone 15 Pro Max 256GB Natural Titanium',
    slug: 'apple-iphone-15-pro-max-256gb-natural-titanium',
    description: 'Titan korpus, eng kuchli A17 Pro chip, 5x optik zoom va USB-C ulanishi. 1 yil rasmiy kafolat bilan.',
    price: 15400000,
    oldPrice: 16900000,
    discount: 9,
    stock: 14,
    sku: 'IPH-15PM-256-NAT',
    brand: 'Apple',
    rating: 4.95,
    reviewCount: 48,
    isFlashSale: true,
    isFeatured: true,
    specifications: {
      'Ekran': '6.7 dyuym Super Retina XDR OLED 120Hz',
      'Protsessor': 'Apple A17 Pro (3 nm)',
      'Xotira': '256 GB NVMe',
      'Tezkor xotira (RAM)': '8 GB',
      'Asosiy kamera': '48 MP + 12 MP (Periscope) + 12 MP',
      'Akkumulyator': '4422 mA/soat, simsiz zaryadlash',
      'SIM karta': 'Dual SIM (nano-SIM + eSIM)'
    },
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-12').toISOString(),
    updatedAt: new Date('2026-01-12').toISOString(),
  },
  // 2
  {
    id: 'prod-samsung-s24-ultra',
    sellerId: 'seller-1',
    categoryId: 'cat-telefonlar',
    name: 'Samsung Galaxy S24 Ultra 12/512GB Titanium Gray',
    slug: 'samsung-galaxy-s24-ultra-12-512gb',
    description: 'Galaxy AI sun\'iy intellekti, o‘rnatilgan S-Pen stilus va 200 MP flagman kamera. O‘zbekiston uchun rasmiy IMEI ro‘yxatidan o‘tgan.',
    price: 14200000,
    oldPrice: 15600000,
    discount: 9,
    stock: 19,
    sku: 'SAM-S24U-512-GRY',
    brand: 'Samsung',
    rating: 4.88,
    reviewCount: 36,
    isFlashSale: true,
    isFeatured: true,
    specifications: {
      'Ekran': '6.8 dyuym Dynamic LTPO AMOLED 2X, 2600 nit',
      'Protsessor': 'Snapdragon 8 Gen 3 for Galaxy',
      'Xotira': '512 GB UFS 4.0',
      'RAM': '12 GB',
      'Asosiy kamera': '200 MP + 50 MP (5x zoom) + 10 MP + 12 MP',
      'Akkumulyator': '5000 mA/soat, 45W tezkor quvvatlash'
    },
    images: [
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-15').toISOString(),
    updatedAt: new Date('2026-01-15').toISOString(),
  },
  // 3
  {
    id: 'prod-redmi-note-13-pro',
    sellerId: 'seller-1',
    categoryId: 'cat-telefonlar',
    name: 'Xiaomi Redmi Note 13 Pro 8/256GB Midnight Black',
    slug: 'xiaomi-redmi-note-13-pro-8-256gb',
    description: '200 MP kamera, 120Hz AMOLED ekran va 67W turbo zaryadlash. Eng ommabop hamyonbop smartfon.',
    price: 3100000,
    oldPrice: 3500000,
    discount: 11,
    stock: 45,
    sku: 'XIA-RN13P-256',
    brand: 'Xiaomi',
    rating: 4.75,
    reviewCount: 92,
    isFlashSale: false,
    isFeatured: true,
    specifications: {
      'Ekran': '6.67 dyuym AMOLED, 120Hz, Dolby Vision',
      'Protsessor': 'MediaTek Helio G99-Ultra',
      'Xotira': '256 GB',
      'RAM': '8 GB',
      'Kamera': '200 MP OIS + 8 MP + 2 MP'
    },
    images: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-20').toISOString(),
    updatedAt: new Date('2026-01-20').toISOString(),
  },
  // 4
  {
    id: 'prod-macbook-pro-14-m3',
    sellerId: 'seller-1',
    categoryId: 'cat-kompyuterlar',
    name: 'Apple MacBook Pro 14" M3 Pro 18GB/512GB Space Black',
    slug: 'apple-macbook-pro-14-m3-pro-18gb-512gb',
    description: 'Dasturchilar va dizaynerlar uchun mo‘ljallangan noutbuk. Liquid Retina XDR ekran va 18 soat batareya ishlash muddati.',
    price: 26800000,
    oldPrice: 28900000,
    discount: 7,
    stock: 8,
    sku: 'MBP-14-M3P-BLK',
    brand: 'Apple',
    rating: 4.98,
    reviewCount: 29,
    isFlashSale: false,
    isFeatured: true,
    specifications: {
      'Ekran': '14.2 dyuym Liquid Retina XDR 120Hz ProMotion',
      'Protsessor': 'Apple M3 Pro (11-yadroli CPU, 14-yadroli GPU)',
      'RAM': '18 GB birlashtirilgan xotira',
      'Xotira': '512 GB SSD',
      'Portlar': 'HDMI, MagSafe 3, SDXC karta uyasi, 3x Thunderbolt 4'
    },
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-08').toISOString(),
    updatedAt: new Date('2026-01-08').toISOString(),
  },
  // 5
  {
    id: 'prod-asus-rog-strix-g16',
    sellerId: 'seller-1',
    categoryId: 'cat-kompyuterlar',
    name: 'ASUS ROG Strix G16 Gaming Laptop (i7-13650HX / RTX 4060 / 16GB / 1TB)',
    slug: 'asus-rog-strix-g16-gaming-laptop',
    description: 'Eng so‘nggi AAA o‘yinlar va 3D modellashtirish uchun mo‘ljallangan o‘yin kompyuteri. 165Hz FHD+ displey.',
    price: 16900000,
    oldPrice: 18500000,
    discount: 9,
    stock: 11,
    sku: 'ASUS-ROG-G16-4060',
    brand: 'ASUS',
    rating: 4.82,
    reviewCount: 22,
    isFlashSale: true,
    isFeatured: true,
    specifications: {
      'Protsessor': 'Intel Core i7-13650HX 14 yadro',
      'Videokarta': 'NVIDIA GeForce RTX 4060 8GB GDDR6',
      'RAM': '16 GB DDR5 4800MHz',
      'Xotira': '1 TB PCIe 4.0 NVMe SSD',
      'Ekran': '16 dyuym FHD+ 165Hz IPS'
    },
    images: [
      'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-14').toISOString(),
    updatedAt: new Date('2026-01-14').toISOString(),
  },
  // 6
  {
    id: 'prod-airpods-pro-2',
    sellerId: 'seller-1',
    categoryId: 'cat-elektronika',
    name: 'Apple AirPods Pro (2nd Gen) MagSafe Case (USB-C)',
    slug: 'apple-airpods-pro-2-usb-c',
    description: 'Faol shovqinni bekor qilish (ANC), Shaffoflik rejimi va moslashtirilgan fazoviy audio texnologiyasi.',
    price: 2850000,
    oldPrice: 3200000,
    discount: 11,
    stock: 35,
    sku: 'APP-PRO2-USBC',
    brand: 'Apple',
    rating: 4.92,
    reviewCount: 114,
    isFlashSale: true,
    isFeatured: true,
    specifications: {
      'Shovqinni bostirish': '2 baravar kuchaytirilgan Active Noise Cancellation',
      'Akkumulyator': '6 soatgacha bir martalik, keys bilan 30 soat',
      'Suvga chidamlilik': 'IP54',
      'Ulanish': 'Bluetooth 5.3, H2 chip'
    },
    images: [
      'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-18').toISOString(),
    updatedAt: new Date('2026-01-18').toISOString(),
  },
  // 7
  {
    id: 'prod-sony-wh-1000xm5',
    sellerId: 'seller-1',
    categoryId: 'cat-elektronika',
    name: 'Sony WH-1000XM5 Wireless Noise-Canceling Headphones Black',
    slug: 'sony-wh-1000xm5-wireless-black',
    description: 'Sanoatdagi yetakchi shovqinni bostirish, kristalldek tiniq qo‘ng‘iroqlar va 30 soatlik batareya quvvati.',
    price: 4300000,
    oldPrice: 4800000,
    discount: 10,
    stock: 12,
    sku: 'SONY-XM5-BLK',
    brand: 'Sony',
    rating: 4.89,
    reviewCount: 41,
    isFlashSale: false,
    isFeatured: true,
    specifications: {
      'Turi': 'Simsiz quloqchin (Over-ear)',
      'Batareya': '30 soat ANC bilan',
      'Tezkor quvvatlash': '3 daqiqada 3 soatlik ish vaqti',
      'Vazni': '250 g'
    },
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-22').toISOString(),
    updatedAt: new Date('2026-01-22').toISOString(),
  },
  // 8
  {
    id: 'prod-jbl-charge-5',
    sellerId: 'seller-1',
    categoryId: 'cat-elektronika',
    name: 'JBL Charge 5 Suv o‘tkazmaydigan Portativ Kolonka Moviy',
    slug: 'jbl-charge-5-portable-speaker-blue',
    description: 'Boy Original Pro Sound ovozi, 20 soat o‘ynash va o‘rnatilgan poverbank funksiyasi.',
    price: 1950000,
    oldPrice: 2300000,
    discount: 15,
    stock: 28,
    sku: 'JBL-CHG5-BLU',
    brand: 'JBL',
    rating: 4.85,
    reviewCount: 65,
    isFlashSale: true,
    isFeatured: false,
    specifications: {
      'Chiqish quvvati': '40W RMS',
      'Akkumulyator': '7500 mA/soat (20 soat musika)',
      'Himoya darajasi': 'IP67 chang va suvga chidamli',
      'Xususiyat': 'PartyBoost orqali bir necha kolonkani ulash'
    },
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-25').toISOString(),
    updatedAt: new Date('2026-01-25').toISOString(),
  },
  // 9
  {
    id: 'prod-nike-air-force-1',
    sellerId: 'seller-2',
    categoryId: 'cat-poyabzal',
    name: 'Nike Air Force 1 \'07 Original Krossovkalari Oq rang',
    slug: 'nike-air-force-1-07-white',
    description: 'Klassik afsonaviy dizayn, mustahkam charm va qulay amortizatsiya. Har kuni kiyish uchun ideal.',
    price: 1250000,
    oldPrice: 1500000,
    discount: 17,
    stock: 30,
    sku: 'NKE-AF1-07-WHT',
    brand: 'Nike',
    rating: 4.86,
    reviewCount: 78,
    isFlashSale: true,
    isFeatured: true,
    specifications: {
      'Material': '100% tabiiy va sun\'iy charm',
      'Taglik': 'Air-Sole amortizatsiyali kauchuk taglik',
      'Mavsum': 'Barcha mavsumlar',
      'O‘lchamlar': '40, 41, 42, 43, 44'
    },
    images: [
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-16').toISOString(),
    updatedAt: new Date('2026-01-16').toISOString(),
  },
  // 10
  {
    id: 'prod-adidas-ultraboost-light',
    sellerId: 'seller-2',
    categoryId: 'cat-poyabzal',
    name: 'Adidas Ultraboost Light Yugurish Krossovkasi Qora',
    slug: 'adidas-ultraboost-light-running-black',
    description: 'Yengil Boost materialidan tayyorlangan zamonaviy yugurish krossovkasi. Maksimal energiya qaytarish.',
    price: 1850000,
    oldPrice: 2200000,
    discount: 16,
    stock: 18,
    sku: 'ADI-UB-LGT-BLK',
    brand: 'Adidas',
    rating: 4.8,
    reviewCount: 34,
    isFlashSale: false,
    isFeatured: true,
    specifications: {
      'Amortizatsiya': 'Light BOOST',
      'Yuqori qism': 'adidas PRIMEKNIT+ matosi',
      'Taglik': 'Continental Better Rubber'
    },
    images: [
      'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-20').toISOString(),
    updatedAt: new Date('2026-01-20').toISOString(),
  },
  // 11
  {
    id: 'prod-hoodie-oversize-beige',
    sellerId: 'seller-2',
    categoryId: 'cat-kiyim',
    name: 'Oversize Xudi Qalin Paxtali Bej Rang',
    slug: 'oversize-hoodie-cotton-beige',
    description: '100% yuqori sifatli zich paxta (3-ipli futer), yumshoq ichki qatlam va zamonaviy keng bichim.',
    price: 340000,
    oldPrice: 450000,
    discount: 24,
    stock: 50,
    sku: 'CLO-HOD-OVZ-BGE',
    brand: 'UrbanTrend',
    rating: 4.7,
    reviewCount: 49,
    isFlashSale: true,
    isFeatured: true,
    specifications: {
      'Tarkibi': '95% paxta, 5% elastan',
      'Zichlik': '360 g/m²',
      'Bichim': 'Oversized unisex'
    },
    images: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-24').toISOString(),
    updatedAt: new Date('2026-01-24').toISOString(),
  },
  // 12
  {
    id: 'prod-classic-men-suit',
    sellerId: 'seller-2',
    categoryId: 'cat-kiyim',
    name: 'Erkaklar uchun Italiya uslubidagi klassik kostyum-shim To‘q ko‘k',
    slug: 'erkaklar-klassik-kostyum-shim-navy',
    description: 'Rasmiy tadbirlar, to‘y va ish uchrashuvlari uchun qulay matoli erkin va qomatga mos bichimli kostyum.',
    price: 1950000,
    oldPrice: 2400000,
    discount: 19,
    stock: 15,
    sku: 'CLO-SUT-NVY-01',
    brand: 'Sartoria Milano',
    rating: 4.9,
    reviewCount: 19,
    isFlashSale: false,
    isFeatured: true,
    specifications: {
      'Tarkibi': '70% jun, 30% viskoza',
      'Astar': '100% ipaksimon viskoza',
      'Komplekt': 'Pidjak va shim'
    },
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-28').toISOString(),
    updatedAt: new Date('2026-01-28').toISOString(),
  },
  // 13
  {
    id: 'prod-dyson-v15-detect',
    sellerId: 'seller-1',
    categoryId: 'cat-uy-rozgor',
    name: 'Dyson V15 Detect Absolute Simsiz Changyutgich',
    slug: 'dyson-v15-detect-absolute-simsiz-changyutgich',
    description: 'Lazerli mikroskopik chang aniqlash tizimi, 240 AW kuchli tortish kuchi va LCD ekran.',
    price: 10200000,
    oldPrice: 11500000,
    discount: 11,
    stock: 9,
    sku: 'DYS-V15-ABS',
    brand: 'Dyson',
    rating: 4.95,
    reviewCount: 31,
    isFlashSale: true,
    isFeatured: true,
    specifications: {
      'Tortish kuchi': '240 AW',
      'Ishlash vaqti': '60 daqiqagacha',
      'Filtratsiya': '99.99% mikroskopik zarralarni tutadi',
      'Konteyner hajmi': '0.77 l'
    },
    images: [
      'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-05').toISOString(),
    updatedAt: new Date('2026-01-05').toISOString(),
  },
  // 14
  {
    id: 'prod-tefal-airfryer-dual',
    sellerId: 'seller-1',
    categoryId: 'cat-uy-rozgor',
    name: 'Tefal Dual Easy Fry & Grill Aerogrili 8.3L',
    slug: 'tefal-dual-easy-fry-and-grill-8-3l',
    description: 'Ikkita mustaqil pishirish bo‘limi, yog‘siz qovurish va panjara tayyorlash. Butun oila uchun sog‘lom taomlar.',
    price: 2450000,
    oldPrice: 2900000,
    discount: 16,
    stock: 22,
    sku: 'TEF-AF-DUAL83',
    brand: 'Tefal',
    rating: 4.85,
    reviewCount: 42,
    isFlashSale: false,
    isFeatured: true,
    specifications: {
      'Hajmi': '8.3 L (5.2L + 3.1L)',
      'Quvvati': '2700 W',
      'Dasturlar': '8 ta avtomatik rejim'
    },
    images: [
      'https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-19').toISOString(),
    updatedAt: new Date('2026-01-19').toISOString(),
  },
  // 15
  {
    id: 'prod-delonghi-magnifica-s',
    sellerId: 'seller-1',
    categoryId: 'cat-uy-rozgor',
    name: 'De\'Longhi Magnifica S Avtomatik Qahva Mashinasi',
    slug: 'delonghi-magnifica-s-ecam22-110-b',
    description: 'Haqiqiy espresso va sutli kapuchino tayyorlash uchun italyancha avtomat kofemashina.',
    price: 5200000,
    oldPrice: 5900000,
    discount: 12,
    stock: 14,
    sku: 'DLN-MAGS-BLK',
    brand: 'DeLonghi',
    rating: 4.88,
    reviewCount: 37,
    isFlashSale: true,
    isFeatured: true,
    specifications: {
      'Nasos bosimi': '15 bar',
      'Don qahva idishi': '250 g',
      'Suv idishi': '1.8 l',
      'Xususiyat': 'Kapuchinator va o‘zini tozalash tizimi'
    },
    images: [
      'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-23').toISOString(),
    updatedAt: new Date('2026-01-23').toISOString(),
  },
  // 16
  {
    id: 'prod-dior-sauvage-edp',
    sellerId: 'seller-2',
    categoryId: 'cat-kosmetika',
    name: 'Dior Sauvage Eau de Parfum 100ml Original',
    slug: 'dior-sauvage-eau-de-parfum-100ml',
    description: 'Kalabriya bergamoti va vanil notalari uyg‘unligi. Erkaklar uchun eng mashhur va uzoq saqlanadigan parfyum.',
    price: 1850000,
    oldPrice: 2150000,
    discount: 14,
    stock: 25,
    sku: 'DIO-SAUV-100',
    brand: 'Dior',
    rating: 4.94,
    reviewCount: 88,
    isFlashSale: true,
    isFeatured: true,
    specifications: {
      'Hajmi': '100 ml',
      'Turi': 'Eau de Parfum (EDP)',
      'Mamlakat': 'Fransiya'
    },
    images: [
      'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-11').toISOString(),
    updatedAt: new Date('2026-01-11').toISOString(),
  },
  // 17
  {
    id: 'prod-lancom-genifique-serum',
    sellerId: 'seller-2',
    categoryId: 'cat-kosmetika',
    name: 'Lancôme Advanced Génifique Yoshartiruvchi Zardob 50ml',
    slug: 'lancome-advanced-genifique-serum-50ml',
    description: 'Mikrobioma texnologiyasi bilan boyitilgan, yuz terisini taranglashtiruvchi va chuqur namlantiruvchi premium sarum.',
    price: 1450000,
    oldPrice: 1700000,
    discount: 15,
    stock: 20,
    sku: 'LAN-GEN-50',
    brand: 'Lancôme',
    rating: 4.9,
    reviewCount: 39,
    isFlashSale: false,
    isFeatured: true,
    specifications: {
      'Hajmi': '50 ml',
      'Qo‘llanishi': 'Yuz va bo‘yin terisi uchun',
      'Xususiyat': 'Probiyotik fraksiyalar, gialuron kislotasi'
    },
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-17').toISOString(),
    updatedAt: new Date('2026-01-17').toISOString(),
  },
  // 18
  {
    id: 'prod-xiaomi-watch-s3',
    sellerId: 'seller-1',
    categoryId: 'cat-elektronika',
    name: 'Xiaomi Watch S3 Smart Soat Kumushrang',
    slug: 'xiaomi-watch-s3-silver',
    description: 'Almashtiriladigan ramkalar, 1.43 dyuym AMOLED displey, 150+ sport rejimlari va 15 kunlik avtonomiya.',
    price: 1450000,
    oldPrice: 1750000,
    discount: 17,
    stock: 32,
    sku: 'XIA-WCH-S3-SLV',
    brand: 'Xiaomi',
    rating: 4.78,
    reviewCount: 46,
    isFlashSale: true,
    isFeatured: false,
    specifications: {
      'Ekran': '1.43" AMOLED 60Hz',
      'Batareya': '15 kungacha (HyperOS)',
      'Suvga chidamlilik': '5 ATM',
      'Datchiklar': 'Yurak urishi, SpO2, uyqu monitoringi, GPS'
    },
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-21').toISOString(),
    updatedAt: new Date('2026-01-21').toISOString(),
  },
  // 19
  {
    id: 'prod-ipad-air-m2',
    sellerId: 'seller-1',
    categoryId: 'cat-telefonlar',
    name: 'Apple iPad Air 11" M2 128GB Wi-Fi Space Gray',
    slug: 'apple-ipad-air-11-m2-128gb',
    description: 'Kuchli M2 chipi, Apple Pencil Pro ko‘magi va yorqin Liquid Retina displey bilan dars va ijod uchun mukammal.',
    price: 8400000,
    oldPrice: 9200000,
    discount: 9,
    stock: 16,
    sku: 'IPA-AIR-M2-128',
    brand: 'Apple',
    rating: 4.93,
    reviewCount: 35,
    isFlashSale: false,
    isFeatured: true,
    specifications: {
      'Ekran': '11 dyuym Liquid Retina True Tone',
      'Protsessor': 'Apple M2 (8 yadro CPU, 9 yadro GPU)',
      'Xotira': '128 GB',
      'Akkumulyator': '10 soatgacha video ko‘rish'
    },
    images: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-26').toISOString(),
    updatedAt: new Date('2026-01-26').toISOString(),
  },
  // 20
  {
    id: 'prod-sony-playstation-5-slim',
    sellerId: 'seller-1',
    categoryId: 'cat-elektronika',
    name: 'Sony PlayStation 5 Slim 1TB Disk Edition',
    slug: 'sony-playstation-5-slim-1tb-disc',
    description: 'Yangi ixcham korpus, 1 TB tezkor SSD xotira va 4K 120Hz geyming imkoniyati. DualSense geympadi bilan.',
    price: 7200000,
    oldPrice: 7900000,
    discount: 9,
    stock: 10,
    sku: 'PS5-SLIM-1TB-DSC',
    brand: 'Sony',
    rating: 4.97,
    reviewCount: 52,
    isFlashSale: true,
    isFeatured: true,
    specifications: {
      'Xotira': '1 TB Custom NVMe SSD',
      'Grafika': '10.28 TFLOPs RDNA 2 GPU',
      'Chiqish': 'HDMI 2.1 (4K 120Hz, 8K, VRR)',
      'O‘lcham': 'PS5 asl modelidan 30% ixchamroq'
    },
    images: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-13').toISOString(),
    updatedAt: new Date('2026-01-13').toISOString(),
  },
  // 21
  {
    id: 'prod-gantel-to\'plami-20kg',
    sellerId: 'seller-2',
    categoryId: 'cat-sport',
    name: 'Yig‘iladigan Gantel va Shtanga To‘plami 20kg Xrom',
    slug: 'yigiladigan-gantel-shtanga-toplami-20kg',
    description: 'Uy sharoitida mushaklarni rivojlantirish uchun to‘liq to‘plam: 2 ta gantel griffi va birlashtiruvchi shtanga trubkasi.',
    price: 490000,
    oldPrice: 620000,
    discount: 21,
    stock: 40,
    sku: 'SPT-DMB-20K-CH',
    brand: 'IronSport',
    rating: 4.74,
    reviewCount: 28,
    isFlashSale: false,
    isFeatured: false,
    specifications: {
      'Og‘irligi': '20 kg umumiy',
      'Qoplama': 'Xromlangan po‘lat',
      'Komplekt': 'Blinlar, 2 griff, rezina ushlagichlar'
    },
    images: [
      'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-27').toISOString(),
    updatedAt: new Date('2026-01-27').toISOString(),
  },
  // 22
  {
    id: 'prod-velosiped-trinx-m136',
    sellerId: 'seller-2',
    categoryId: 'cat-sport',
    name: 'Tog‘ Velosipedi Trinx M136 Pro 29" Gidravlik Tormoz',
    slug: 'trinx-m136-pro-29-mountain-bike',
    description: 'Alyuminiy yengil rama, 21 ta tezlik pog‘onasi, Shimano uzatgichlari va 29 dyuymli g‘ildiraklar.',
    price: 2800000,
    oldPrice: 3300000,
    discount: 15,
    stock: 12,
    sku: 'BIK-TRX-M136-29',
    brand: 'Trinx',
    rating: 4.81,
    reviewCount: 19,
    isFlashSale: true,
    isFeatured: true,
    specifications: {
      'G‘ildirak diametri': '29 dyuym',
      'Rama': 'Alloy 6061',
      'Uzatkich': 'Shimano Tourney 21 tezlik',
      'Tormoz': 'Gidravlik diskli'
    },
    images: [
      'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-29').toISOString(),
    updatedAt: new Date('2026-01-29').toISOString(),
  },
  // 23
  {
    id: 'prod-atom-odatlari-kitob',
    sellerId: 'seller-2',
    categoryId: 'cat-kitoblar',
    name: 'Atom Odatlari (Jeyms Klir) — O‘zbek tilida (Qattiq muqova)',
    slug: 'atom-odatlari-jeyms-klir-kitob',
    description: 'Kichik o‘zgarishlar — ulkan natijalar. Butun dunyo bo‘yicha 15 milliondan ortiq sotilgan bestseller asar.',
    price: 65000,
    oldPrice: 85000,
    discount: 24,
    stock: 120,
    sku: 'BOK-ATM-ODT-UZ',
    brand: 'Nihol Nashriyoti',
    rating: 4.96,
    reviewCount: 180,
    isFlashSale: true,
    isFeatured: true,
    specifications: {
      'Muallif': 'Jeyms Klir (James Clear)',
      'Til': 'O‘zbekcha (Lotin alifbosi)',
      'Sahifalar soni': '320 bet',
      'Muqova': 'Qattiq muqova'
    },
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-03').toISOString(),
    updatedAt: new Date('2026-01-03').toISOString(),
  },
  // 24
  {
    id: 'prod-stiv-jobs-biografiya',
    sellerId: 'seller-2',
    categoryId: 'cat-kitoblar',
    name: 'Stiv Jobs — Uolt Ayzekson (Katta ensiklopedik nashr)',
    slug: 'stiv-jobs-uolt-ayzekson-kitob',
    description: 'Texnologiyalar olamining eng mashhur inqilobchisi Stiv Jobsning yagona rasmiy biografiyasi.',
    price: 95000,
    oldPrice: 120000,
    discount: 21,
    stock: 65,
    sku: 'BOK-STV-JBS-UZ',
    brand: 'Hilol Nashr',
    rating: 4.92,
    reviewCount: 67,
    isFlashSale: false,
    isFeatured: false,
    specifications: {
      'Muallif': 'Uolter Ayzekson',
      'Sahifalar': '640 bet',
      'Muqova': 'Zarhal qattiq muqova'
    },
    images: [
      'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-07').toISOString(),
    updatedAt: new Date('2026-01-07').toISOString(),
  },
  // 25
  {
    id: 'prod-70mai-dashcam-a810',
    sellerId: 'seller-1',
    categoryId: 'cat-avto',
    name: '70mai Dash Cam 4K A810 Avtomobil Videoregistratori',
    slug: '70mai-dash-cam-4k-a810-videoregistrator',
    description: 'Sony Starvis 2 sensori, haqiqiy 4K UHD tasvir, tungi HDR ko‘rish va orqa kamera qo‘llab-quvvatlash.',
    price: 1850000,
    oldPrice: 2200000,
    discount: 16,
    stock: 22,
    sku: 'AVT-70M-A810',
    brand: '70mai',
    rating: 4.87,
    reviewCount: 38,
    isFlashSale: false,
    isFeatured: true,
    specifications: {
      'Ruxsat': '4K UHD 3840x2160 @60fps',
      'Sensor': 'Sony IMX678',
      'Ko‘rish burchagi': '150 daraja keng burchak',
      'Xususiyat': 'O‘rnatilgan GPS, ADAS xavfsizlik ogohlantirish'
    },
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-14').toISOString(),
    updatedAt: new Date('2026-01-14').toISOString(),
  },
  // 26
  {
    id: 'prod-baseus-car-vacuum',
    sellerId: 'seller-1',
    categoryId: 'cat-avto',
    name: 'Baseus A3 Simsiz Avtomobil Changyutgichi 15000Pa',
    slug: 'baseus-a3-simsiz-avtomobil-changyutgichi',
    description: 'Metall korpus, kuchli 15000Pa so‘rish quvvati, o‘rnatilgan chiroq va ixcham qulay saqlash.',
    price: 520000,
    oldPrice: 650000,
    discount: 20,
    stock: 35,
    sku: 'AVT-BAS-A3-VAC',
    brand: 'Baseus',
    rating: 4.79,
    reviewCount: 54,
    isFlashSale: true,
    isFeatured: false,
    specifications: {
      'Quvvat': '15000 Pa',
      'Batareya': '4x2000 mA/soat (50 min)',
      'Zaryadlash': 'Type-C QC 3.0'
    },
    images: [
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-18').toISOString(),
    updatedAt: new Date('2026-01-18').toISOString(),
  },
  // 27
  {
    id: 'prod-lego-technic-ferrari',
    sellerId: 'seller-2',
    categoryId: 'cat-bolalar',
    name: 'LEGO Technic Ferrari Daytona SP3 Konstruktori (3778 detal)',
    slug: 'lego-technic-ferrari-daytona-sp3',
    description: 'Haqiqiy V12 dvigatel harakati, 8 bosqichli uzatmalar qutisi va kapalak eshiklar. Kolleksionerlar uchun.',
    price: 4900000,
    oldPrice: 5600000,
    discount: 13,
    stock: 7,
    sku: 'KID-LEG-42143',
    brand: 'LEGO',
    rating: 4.98,
    reviewCount: 23,
    isFlashSale: false,
    isFeatured: true,
    specifications: {
      'Detallar soni': '3778 dona',
      'Masshtab': '1:8',
      'Yosh chegarasi': '18+'
    },
    images: [
      'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-22').toISOString(),
    updatedAt: new Date('2026-01-22').toISOString(),
  },
  // 28
  {
    id: 'prod-kolyaska-chico-trio',
    sellerId: 'seller-2',
    categoryId: 'cat-bolalar',
    name: 'Chicco Trio Best Friend Pro Bolalar Aravachasi 3 tasi 1 da',
    slug: 'chicco-trio-best-friend-pro-aravacha',
    description: 'Lyulka, sayr bloki va avtokreslo jamlanmasi. Amortizatorli yengil shassi va qulay buklanish.',
    price: 6400000,
    oldPrice: 7200000,
    discount: 11,
    stock: 6,
    sku: 'KID-CHC-TR3-BLK',
    brand: 'Chicco',
    rating: 4.88,
    reviewCount: 16,
    isFlashSale: false,
    isFeatured: true,
    specifications: {
      'Komplektatsiya': 'Lyulka + sayr aravachasi + avto lyulka 0+',
      'Og‘irligi': '11.2 kg',
      'Ishlab chiqaruvchi': 'Italiya'
    },
    images: [
      'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-25').toISOString(),
    updatedAt: new Date('2026-01-25').toISOString(),
  },
  // 29
  {
    id: 'prod-samsonite-chomodani',
    sellerId: 'seller-2',
    categoryId: 'cat-boshqa',
    name: 'Samsonite Lite-Box Spinner 75cm Yengil Chemodan',
    slug: 'samsonite-lite-box-spinner-75cm',
    description: 'Curv revolyutsion materialidan tayyorlangan zarbaga chidamli, o‘ta yengil va TSA kodli qulfli sayohat chemodani.',
    price: 3800000,
    oldPrice: 4400000,
    discount: 14,
    stock: 15,
    sku: 'OTH-SAM-LB75',
    brand: 'Samsonite',
    rating: 4.91,
    reviewCount: 27,
    isFlashSale: true,
    isFeatured: false,
    specifications: {
      'Hajmi': '98 litr',
      'Vazni': '3.1 kg',
      'G‘ildiraklar': '4 ta ikki qatorli 360° manyovrli g‘ildiraklar',
      'Qulf': 'O‘rnatilgan TSA raqamli qulf'
    },
    images: [
      'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-27').toISOString(),
    updatedAt: new Date('2026-01-27').toISOString(),
  },
  // 30
  {
    id: 'prod-kindle-paperwhite-11',
    sellerId: 'seller-1',
    categoryId: 'cat-kitoblar',
    name: 'Amazon Kindle Paperwhite 11-avlod 16GB Suv o‘tkazmaydigan',
    slug: 'amazon-kindle-paperwhite-11-16gb',
    description: '6.8 dyuymli aks etmaydigan 300 ppi E-Ink displey, iliq yoritish nuri va 10 haftalik batareya quvvati.',
    price: 2150000,
    oldPrice: 2450000,
    discount: 12,
    stock: 24,
    sku: 'AMZ-KND-PW11',
    brand: 'Amazon',
    rating: 4.94,
    reviewCount: 62,
    isFlashSale: false,
    isFeatured: true,
    specifications: {
      'Ekran': '6.8" Paperwhite 300 ppi',
      'Xotira': '16 GB (minglab kitoblar)',
      'Suvga chidamlilik': 'IPX8 (2 metrgacha chuchuk suv)',
      'Yoritish': 'Oq va iliq sarg‘ish tonlarni sozlash'
    },
    images: [
      'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-01-30').toISOString(),
    updatedAt: new Date('2026-01-30').toISOString(),
  },
  // 31
  {
    id: 'prod-smart-choynak-xiaomi',
    sellerId: 'seller-1',
    categoryId: 'cat-uy-rozgor',
    name: 'Xiaomi Mi Smart Kettle Pro Elektr Choynak',
    slug: 'xiaomi-mi-smart-kettle-pro-elektr-choynak',
    description: 'Raqamli harorat ko‘rsatkichli displey, 5 xil haroratni ushlab turish rejimi va Mi Home ilovasi orqali boshqaruv.',
    price: 490000,
    oldPrice: 580000,
    discount: 16,
    stock: 45,
    sku: 'XIA-KET-PRO',
    brand: 'Xiaomi',
    rating: 4.76,
    reviewCount: 84,
    isFlashSale: true,
    isFeatured: false,
    specifications: {
      'Hajmi': '1.5 litr',
      'Quvvati': '1800 W',
      'Material': 'Oziq-ovqat zanglamas po‘lati 304',
      'Harorat rejimlari': '40°C, 50°C, 70°C, 80°C, 90°C'
    },
    images: [
      'https://images.unsplash.com/photo-1594213114663-d94db9b17125?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-02-01').toISOString(),
    updatedAt: new Date('2026-02-01').toISOString(),
  },
  // 32
  {
    id: 'prod-anker-soundcore-motion-plus',
    sellerId: 'seller-1',
    categoryId: 'cat-elektronika',
    name: 'Anker Soundcore Motion+ 30W Hi-Res Bluetooth Dinamik',
    slug: 'anker-soundcore-motion-plus-hi-res',
    description: 'Hi-Res Audio sertifikatlangan, BassUp texnologiyasi, ultra keng chastota diapazoni (50Hz - 40kHz).',
    price: 1100000,
    oldPrice: 1350000,
    discount: 19,
    stock: 18,
    sku: 'ANK-MOT-PLUS',
    brand: 'Anker',
    rating: 4.88,
    reviewCount: 39,
    isFlashSale: true,
    isFeatured: false,
    specifications: {
      'Quvvat': '30 Watt',
      'Batareya': '6700 mA/soat (12 soat)',
      'Suvga chidamlilik': 'IPX7',
      'Ulanish': 'Bluetooth 5.0, Qualcomm aptX'
    },
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80'
    ],
    status: 'APPROVED',
    createdAt: new Date('2026-02-02').toISOString(),
    updatedAt: new Date('2026-02-02').toISOString(),
  }
];

export const initialOrders: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'BZ-2026-0891',
    userId: 'user-customer-1',
    subtotal: 15400000,
    deliveryFee: 0,
    total: 15400000,
    status: 'DELIVERED',
    paymentMethod: 'CLICK',
    paymentStatus: 'PAID',
    shippingAddress: {
      fullName: 'Anvar Karimov',
      phone: '+998971112233',
      region: 'Toshkent shahri',
      city: 'Yunusobod tumani',
      addressLine: 'Amir Temur ko‘chasi, 107A-uy, 45-xonadon',
      notes: 'Iltimos, yetkazishdan oldin telefon qiling.'
    },
    notes: 'Kuryer orqali yetkazildi',
    createdAt: new Date('2026-02-10T14:30:00').toISOString(),
    updatedAt: new Date('2026-02-11T16:00:00').toISOString(),
    items: [
      {
        id: 'ord-item-1',
        orderId: 'ord-1001',
        productId: 'prod-iphone-15-pro-max',
        name: 'Apple iPhone 15 Pro Max 256GB Natural Titanium',
        price: 15400000,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
        createdAt: new Date('2026-02-10T14:30:00').toISOString(),
      }
    ]
  },
  {
    id: 'ord-1002',
    orderNumber: 'BZ-2026-0942',
    userId: 'user-customer-1',
    subtotal: 2850000,
    deliveryFee: 0,
    total: 2850000,
    status: 'SHIPPED',
    paymentMethod: 'PAYME',
    paymentStatus: 'PAID',
    shippingAddress: {
      fullName: 'Anvar Karimov',
      phone: '+998971112233',
      region: 'Toshkent shahri',
      city: 'Yunusobod tumani',
      addressLine: 'Amir Temur ko‘chasi, 107A-uy, 45-xonadon'
    },
    notes: 'Kuryer yo‘lda, bugun soat 18:00 gacha yetkaziladi',
    createdAt: new Date('2026-03-01T10:15:00').toISOString(),
    updatedAt: new Date('2026-03-02T09:00:00').toISOString(),
    items: [
      {
        id: 'ord-item-2',
        orderId: 'ord-1002',
        productId: 'prod-airpods-pro-2',
        name: 'Apple AirPods Pro (2nd Gen) MagSafe Case (USB-C)',
        price: 2850000,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&auto=format&fit=crop&q=80',
        createdAt: new Date('2026-03-01T10:15:00').toISOString(),
      }
    ]
  },
  {
    id: 'ord-1003',
    orderNumber: 'BZ-2026-1055',
    userId: 'user-customer-1',
    subtotal: 405000,
    deliveryFee: 25000,
    total: 430000,
    status: 'CONFIRMED',
    paymentMethod: 'CASH',
    paymentStatus: 'PENDING',
    shippingAddress: {
      fullName: 'Anvar Karimov',
      phone: '+998971112233',
      region: 'Toshkent shahri',
      city: 'Yunusobod tumani',
      addressLine: 'Amir Temur ko‘chasi, 107A-uy, 45-xonadon'
    },
    notes: 'Qabul qilganda naqd pul orqali to‘lanadi',
    createdAt: new Date('2026-03-05T18:20:00').toISOString(),
    updatedAt: new Date('2026-03-05T18:25:00').toISOString(),
    items: [
      {
        id: 'ord-item-3',
        orderId: 'ord-1003',
        productId: 'prod-hoodie-oversize-beige',
        name: 'Oversize Xudi Qalin Paxtali Bej Rang',
        price: 340000,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
        createdAt: new Date('2026-03-05T18:20:00').toISOString(),
      },
      {
        id: 'ord-item-4',
        orderId: 'ord-1003',
        productId: 'prod-atom-odatlari-kitob',
        name: 'Atom Odatlari (Jeyms Klir) — O‘zbek tilida (Qattiq muqova)',
        price: 65000,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
        createdAt: new Date('2026-03-05T18:20:00').toISOString(),
      }
    ]
  }
];

export const initialReviews: Review[] = [
  {
    id: 'rev-1',
    userId: 'user-customer-1',
    productId: 'prod-iphone-15-pro-max',
    userName: 'Anvar Karimov',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Mahsulot original, qutisida ochilmagan holda yetkazildi. IMEI darhol ro‘yxatdan o‘tdi. Rahmat TechnoMall!',
    createdAt: new Date('2026-02-12').toISOString(),
  },
  {
    id: 'rev-2',
    userId: 'user-customer-1',
    productId: 'prod-airpods-pro-2',
    userName: 'Anvar Karimov',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Shovqinni bekor qilishi juda ajoyib, metroda umuman shovqin eshitilmaydi. Ovozi juda toza!',
    createdAt: new Date('2026-03-03').toISOString(),
  },
  {
    id: 'rev-3',
    userId: 'user-seller-1',
    productId: 'prod-macbook-pro-14-m3',
    userName: 'Sardor Rustamov',
    rating: 5,
    comment: 'M3 Pro chip dasturlash va Docker bilan ishlashda qizimaydi ham. Batareyasi bir kunga yetadi.',
    createdAt: new Date('2026-01-25').toISOString(),
  },
  {
    id: 'rev-4',
    userId: 'user-customer-1',
    productId: 'prod-atom-odatlari-kitob',
    userName: 'Kamola Saidova',
    rating: 5,
    comment: 'O‘zbek tiliga juda chiroyli tarjima qilingan. Har bir yosh o‘qishi kerak bo‘lgan ajoyib asar.',
    createdAt: new Date('2026-02-05').toISOString(),
  }
];

export const initialNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-customer-1',
    title: 'Buyurtmangiz yetkazildi! 🎉',
    message: 'BZ-2026-0891 raqamli buyurtmangiz muvaffaqiyatli topshirildi. Xaridingiz uchun tashakkur!',
    type: 'ORDER',
    isRead: false,
    createdAt: new Date('2026-02-11T16:00:00').toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'user-customer-1',
    title: 'Hafta chegirmalari boshlandi! 🔥',
    message: 'Flash Sale bo‘limida Apple va Samsung qurilmalariga 20% gacha maxsus chegirmalar.',
    type: 'PROMO',
    isRead: true,
    createdAt: new Date('2026-03-01T09:00:00').toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'user-seller-1',
    title: 'Yangi buyurtma qabul qilindi! 📦',
    message: 'Do‘koningizdan yangi buyurtma berildi (BZ-2026-1055). Buyurtmani tayyorlashni boshlang.',
    type: 'ORDER',
    isRead: false,
    createdAt: new Date('2026-03-05T18:20:00').toISOString(),
  },
  {
    id: 'notif-4',
    userId: 'user-admin-1',
    title: 'Yangi sotuvchi ro‘yxatdan o‘tdi 🏪',
    message: 'Yangi sotuvchi hisobi tasdiqlash uchun admin panelga yuborildi.',
    type: 'SYSTEM',
    isRead: false,
    createdAt: new Date('2026-03-06T11:00:00').toISOString(),
  }
];
